### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by dimmduh** [deniszykov/t4-templates-unity3d#1]
Hi!

Can you help me - how to compile project?
I'm opened in Rider and getting many errors.
It seems the project is very related your PC setup

**Comment by deniszykov** [comment]
this project is Unity plugin and it's depends on UnityEngine and UnityEditor assemblies. There is no official Unity reference package and committing dlls into repo is pure evil. So if you want to compile project you need to reference your local Unity dlls.

**Comment by mhgamework** [comment]
Im trying to use the t4 processor, when i select a .tt file in the unity project window , it does not show anything in the inspector. I added the gamedevware dll to the Assets/Editor folder. Anything i am missing?

**Comment by deniszykov** [comment]
Hi @mhgamework! Could you provide more information about:
- version of plugin
- version of Unity
- OS
- Unity's scripting runtime (2.0, 4.0, netstandard)
- editor logs if available with _Verbose Logs_ checked in **Menu** -> **Tools** -> **T4** -> **Verbose Logs**
