### ISSUE TITLE
"TemplateProcessingError" is not helpful when something goes wrong

### ISSUE THREAD

**Issue by TannerMoore** [deniszykov/t4-templates-unity3d#2]
What is your suggested workflow for tweaking/tuning a template? The output in the Unity console is not helpful.

**Comment by deniszykov** [comment]
I have added better error messages in Unity console in da2bab290f0c2846aeb21622b8b86e1176b0479e.
But I recomment to use some external T4 editor for development/debugging purpose.
[Tangible T4 for VS](https://t4-editor.tangible-engineering.com/)
[ForTea for ReSharper](https://plugins.jetbrains.com/plugin/11634-fortea)
[Devart T4 Editor for VS](https://www.devart.com/t4-editor/)

You could temporary [add](https://docs.microsoft.com/en-us/visualstudio/modeling/t4-assembly-directive?view=vs-2019) UnityEngine, UnityEditor and Assembly-CSharp references for VS debugging purpose and delete them later.

**Comment by TannerMoore** [comment]
Thank you for this!
